# Generated by Django 3.1.2 on 2021-06-22 02:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('weeb_downloader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
