# Generated by Django 3.1.2 on 2021-06-22 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeb_downloader', '0002_auto_20210622_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
