# Generated by Django 3.1.2 on 2021-06-23 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeb_downloader', '0005_auto_20210623_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='episode_count',
            field=models.IntegerField(default=0),
        ),
    ]
