# Generated by Django 3.1.2 on 2021-06-23 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeb_downloader', '0006_auto_20210623_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='anime_url',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
