# Generated by Django 3.1.2 on 2021-06-26 11:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('weeb_downloader', '0007_auto_20210624_0146'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadedAnime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('episodes', models.CharField(max_length=100000)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weeb_downloader.anime')),
            ],
        ),
    ]
