# Generated by Django 3.1.2 on 2021-06-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeb_downloader', '0008_downloadedanime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadedanime',
            name='episodes',
            field=models.JSONField(),
        ),
    ]
